apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: nemo260/ambulance-ufe
  newName: nemo260/ambulance-ufe
  newTag: 1.1.0  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
- name: nemo260/ambulance-wl-webapi
  newName: nemo260/ambulance-wl-webapi
  newTag: 1.1.0
- name: nemo261/doc-doc-fe
  newName: nemo261/doc-doc-fe
  newTag: 1.0.0

replacements:
 - targets:
   - select:
         group: fe.milung.eu
         version: v1
         kind: WebComponent
         name: nemo260-ambulance-ufe
     fieldPaths:
         - spec.hash-suffix
   source:
     version: v1
     kind: Deployment
     name:  nemo260-ambulance-ufe-deployment
     fieldPath: spec.template.spec.containers.0.image
     options:
         delimiter: ':'
         index: 1

 - targets:
   - select:
         group: fe.milung.eu
         version: v1
         kind: WebComponent
         name: nemo261-doc-doc-fe
     fieldPaths:
         - spec.hash-suffix
   source:
     version: v1
     kind: Deployment
     name:  nemo261-doc-doc-fe-deployment
     fieldPath: spec.template.spec.containers.0.image