apiVersion: apps/v1
kind: Deployment
metadata:
  name: nemo260-ambulance-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /nemo260-openapi
            - name: BASE_URL
              value: /nemo260-openapi-ui