apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: nemo260/ambulance-ufe
  newName: nemo260/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20240304.1433 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}

- name: milung/ufe-controller
  newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
  newTag: 1.7.3 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}

- name: nemo260/ambulance-wl-webapi
  newName: nemo260/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main.20240325.1325 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}

- name: nemo260/doc-doc-fe 
  newName: nemo260/doc-doc-fe # {"$imagepolicy":  "wac-hospital:doc-doc-fe:name"}
  newTag: main # {"$imagepolicy": "wac-hospital:doc-doc-fe:tag"}
